version: "3.8"

services:
  mongo_db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - .docker/mongo:/data/db

  backend:
    build: .
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    expose:
      - "3000"
    depends_on:
      - mongo_db

volumes:
  db: